import type { BuildingDef, BuildingType } from './types';

export const BUILDING_DEFS: Record<BuildingType, BuildingDef> = {
  dirt_road: {
    type: 'dirt_road', name: 'Dirt Track', category: 'civic',
    desc: 'Cheap access for the edges of the map. Jams the moment anyone uses it.',
    w: 1, h: 1, cost: 3, upkeep: 0.02, jobs: 0, housing: 0,
    power: 0, water: 0, compute: 0, pollution: 0, income: 0, buildTicks: 1,
    roadCapacity: 4, roadType: 0,
  },
  road: {
    type: 'road', name: 'Street', category: 'civic',
    desc: 'The default. Connects districts; workplaces need a route to housing.',
    w: 1, h: 1, cost: 10, upkeep: 0.1, jobs: 0, housing: 0,
    power: 0, water: 0, compute: 0, pollution: 0, income: 0, buildTicks: 1,
    roadCapacity: 10, roadType: 1,
  },
  avenue: {
    type: 'avenue', name: 'Avenue', category: 'civic',
    desc: 'Four lanes and a median. Twice the throughput of a street.',
    w: 1, h: 1, cost: 26, upkeep: 0.25, jobs: 0, housing: 0,
    power: 0, water: 0, compute: 0, pollution: 0, income: 0, buildTicks: 1,
    roadCapacity: 22, roadType: 2, unlockTier: 1,
  },
  highway: {
    type: 'highway', name: 'Highway', category: 'civic',
    desc: 'Regional arterial. Enormous capacity, enormous footprint in every sense.',
    w: 1, h: 1, cost: 60, upkeep: 0.6, jobs: 0, housing: 0,
    power: 0, water: 0, compute: 0, pollution: 0.05, income: 0, buildTicks: 1,
    roadCapacity: 45, roadType: 3, unlockTier: 2,
  },
  house: {
    type: 'house', name: 'House', category: 'zone',
    desc: 'Low-density housing for 6 residents.',
    w: 1, h: 1, cost: 40, upkeep: 0, jobs: 0, housing: 6,
    power: -1, water: -1, compute: 0, pollution: 0, income: 1.2, buildTicks: 2,
  },
  apartment: {
    type: 'apartment', name: 'Apartment Block', category: 'zone',
    desc: 'Dense housing for 40 residents.',
    w: 2, h: 2, cost: 220, upkeep: 1, jobs: 2, housing: 40,
    power: -5, water: -5, compute: 0, pollution: 0, income: 7, buildTicks: 4,
  },
  midrise: {
    type: 'midrise', name: 'Mid-Rise Block', category: 'zone',
    desc: 'Six storeys, courtyard, ground-floor shops. Houses 90.',
    w: 2, h: 2, cost: 420, upkeep: 2, jobs: 6, housing: 90,
    power: -10, water: -10, compute: 0, pollution: 0, income: 15, buildTicks: 5,
    unlockTier: 1, amenity: 0.2,
  },
  highrise: {
    type: 'highrise', name: 'High-Rise Tower', category: 'zone',
    desc: 'Dense vertical housing for 200. The skyline starts here.',
    w: 3, h: 3, cost: 950, upkeep: 5, jobs: 12, housing: 200,
    power: -24, water: -22, compute: 0, pollution: 0, income: 34, buildTicks: 7,
    unlockTier: 2,
  },
  arcology: {
    type: 'arcology', name: 'Arcology', category: 'zone',
    desc: 'A self-contained vertical district of 450. Everything you need, inside.',
    w: 4, h: 4, cost: 2400, upkeep: 14, jobs: 40, housing: 450,
    power: -60, water: -50, compute: 0, pollution: 0, income: 80, buildTicks: 12,
    unlockTier: 3, amenity: 0.4, services: 0.3,
  },
  park: {
    type: 'park', name: 'Park', category: 'amenity',
    desc: 'Green space. Improves health, connection, and the case for living here.',
    w: 2, h: 2, cost: 60, upkeep: 0.5, jobs: 1, housing: 0,
    power: 0, water: -1, compute: 0, pollution: -0.4, income: 0, buildTicks: 2,
    amenity: 1,
  },
  plaza: {
    type: 'plaza', name: 'Civic Plaza', category: 'amenity',
    desc: 'Ceremonial public space with a statue.',
    w: 2, h: 2, cost: 80, upkeep: 0.4, jobs: 1, housing: 0,
    power: -1, water: 0, compute: 0, pollution: 0, income: 0, buildTicks: 2,
    amenity: 0.8,
  },
  school: {
    type: 'school', name: 'School', category: 'amenity',
    desc: 'Educates the next workforce. Parents will not move somewhere without one.',
    w: 3, h: 2, cost: 260, upkeep: 3, jobs: 30, housing: 0,
    power: -5, water: -4, compute: 0, pollution: 0, income: 0, buildTicks: 4,
    amenity: 0.6, services: 1.6,
  },
  library: {
    type: 'library', name: 'Public Library', category: 'amenity',
    desc: 'Books, warmth, wifi, and the region\'s most stubbornly human institution.',
    w: 2, h: 2, cost: 160, upkeep: 1.5, jobs: 10, housing: 0,
    power: -3, water: -1, compute: 0, pollution: 0, income: 0, buildTicks: 3,
    amenity: 1, services: 0.7,
  },
  sports_complex: {
    type: 'sports_complex', name: 'Sports Complex', category: 'amenity',
    desc: 'Pitches, pool, and leagues. Health and belonging, sweatily acquired.',
    w: 3, h: 3, cost: 340, upkeep: 3.5, jobs: 18, housing: 0,
    power: -8, water: -8, compute: 0, pollution: 0, income: 5, buildTicks: 4,
    amenity: 1.8, services: 0.4,
  },
  museum: {
    type: 'museum', name: 'Museum', category: 'amenity',
    desc: 'Cultural anchor. Draws visitors, residents, and arguments about funding.',
    w: 3, h: 2, cost: 420, upkeep: 4, jobs: 22, housing: 0,
    power: -7, water: -3, compute: 0, pollution: 0, income: 7, buildTicks: 5,
    unlockTier: 1, amenity: 2, services: 0.3,
  },
  community_center: {
    type: 'community_center', name: 'Community Center', category: 'amenity',
    desc: 'Clubs, classes, and a hall anyone can book. Where strangers become neighbors.',
    w: 2, h: 2, cost: 180, upkeep: 2, jobs: 12, housing: 0,
    power: -4, water: -3, compute: 0, pollution: 0, income: 0, buildTicks: 3,
    amenity: 1.1, services: 0.8,
  },
  solar_farm: {
    type: 'solar_farm', name: 'Solar Farm', category: 'power',
    desc: 'Clean power. Needs land, delivers modest output.',
    w: 3, h: 3, cost: 260, upkeep: 1.5, jobs: 4, housing: 0,
    power: 22, water: 0, compute: 0, pollution: 0, income: 0, buildTicks: 3, serviceRadius: 9,
  },
  coal_plant: {
    type: 'coal_plant', name: 'Coal Plant', category: 'power',
    desc: 'Cheap, abundant power. The smoke goes somewhere.',
    w: 3, h: 3, cost: 320, upkeep: 3, jobs: 30, housing: 0,
    power: 70, water: -8, compute: 0, pollution: 3.2, income: 0, buildTicks: 4, serviceRadius: 13,
  },
  nuclear_plant: {
    type: 'nuclear_plant', name: 'Nuclear Plant', category: 'power',
    desc: 'Enormous clean output. Expensive, slow to build.',
    w: 4, h: 4, cost: 1400, upkeep: 10, jobs: 45, housing: 0,
    power: 220, water: -25, compute: 0, pollution: 0.1, income: 0, buildTicks: 10, serviceRadius: 20,
    unlockCompute: 60,
  },
  water_plant: {
    type: 'water_plant', name: 'Water Treatment Plant', category: 'power',
    desc: 'Supplies water to homes, industry, and cooling.',
    w: 2, h: 2, cost: 180, upkeep: 1.5, jobs: 10, housing: 0,
    power: -4, water: 60, compute: 0, pollution: 0, income: 0, buildTicks: 3, serviceRadius: 11,
  },
  solar_array: {
    type: 'solar_array', name: 'Solar Array', category: 'power',
    desc: 'Utility-scale panels with tracking mounts. Three times a farm\'s output.',
    w: 4, h: 4, cost: 780, upkeep: 3.5, jobs: 10, housing: 0,
    power: 72, water: 0, compute: 0, pollution: 0, income: 0, buildTicks: 5, serviceRadius: 15,
    unlockTier: 1,
  },
  water_reclamation: {
    type: 'water_reclamation', name: 'Water Reclamation Works', category: 'power',
    desc: 'Closed-loop recycling. Doubles yield from the same watershed.',
    w: 3, h: 3, cost: 640, upkeep: 5, jobs: 24, housing: 0,
    power: -14, water: 150, compute: 0, pollution: 0, income: 0, buildTicks: 6, serviceRadius: 17,
    unlockTier: 2,
  },
  hospital: {
    type: 'hospital', name: 'Hospital', category: 'civic',
    desc: 'Care capacity. AI diagnostics multiply its reach.',
    w: 3, h: 3, cost: 420, upkeep: 5, jobs: 60, housing: 0,
    power: -8, water: -6, compute: 0, pollution: 0, income: 0, buildTicks: 5,
    services: 2.4,
  },
  factory: {
    type: 'factory', name: 'Factory', category: 'industry',
    desc: 'Manufacturing. Many jobs, steady revenue, real smoke.',
    w: 3, h: 3, cost: 300, upkeep: 2, jobs: 60, housing: 0,
    power: -12, water: -6, compute: 0, pollution: 2.0, income: 16, buildTicks: 4,
  },
  auto_factory: {
    type: 'auto_factory', name: 'Automated Factory', category: 'industry',
    desc: 'Higher output, six employees, no lunch breaks.',
    w: 3, h: 3, cost: 520, upkeep: 3, jobs: 6, housing: 0,
    power: -18, water: -6, compute: 0, pollution: 1.2, income: 30, buildTicks: 4,
    unlockCompute: 30,
  },
  office: {
    type: 'office', name: 'Office Tower', category: 'industry',
    desc: 'Service-sector employment and tax revenue.',
    w: 2, h: 2, cost: 260, upkeep: 2, jobs: 40, housing: 0,
    power: -8, water: -3, compute: 0, pollution: 0, income: 14, buildTicks: 4,
  },
  retail: {
    type: 'retail', name: 'Retail Strip', category: 'industry',
    desc: 'Shops and services. Converts wages into revenue.',
    w: 2, h: 2, cost: 140, upkeep: 1, jobs: 20, housing: 0,
    power: -4, water: -2, compute: 0, pollution: 0, income: 8, buildTicks: 3,
  },
  edge_dc: {
    type: 'edge_dc', name: 'Edge Compute Node', category: 'compute',
    desc: 'Small local compute for responsive services.',
    w: 2, h: 2, cost: 200, upkeep: 2, jobs: 4, housing: 0,
    power: -10, water: -5, compute: 12, pollution: 0.2, income: 4, buildTicks: 3,
  },
  cloud_dc: {
    type: 'cloud_dc', name: 'Cloud Data Center', category: 'compute',
    desc: 'Serious capacity. Serious cooling requirements.',
    w: 3, h: 3, cost: 520, upkeep: 5, jobs: 12, housing: 0,
    power: -34, water: -22, compute: 48, pollution: 0.5, income: 14, buildTicks: 5,
    unlockCompute: 12,
  },
  ai_campus: {
    type: 'ai_campus', name: 'AI Training Campus', category: 'compute',
    desc: 'Hyperscale training. The grid will notice.',
    w: 4, h: 4, cost: 1200, upkeep: 12, jobs: 20, housing: 0,
    power: -95, water: -60, compute: 150, pollution: 1.0, income: 40, buildTicks: 8,
    unlockCompute: 60,
  },
  gov_dc: {
    type: 'gov_dc', name: 'Government Secure Facility', category: 'compute',
    desc: 'Hardened compute for state services. And other state functions.',
    w: 3, h: 3, cost: 620, upkeep: 7, jobs: 15, housing: 0,
    power: -22, water: -12, compute: 30, pollution: 0.3, income: 0, buildTicks: 6,
    unlockCompute: 40,
  },
  med_dc: {
    type: 'med_dc', name: 'Medical Compute Center', category: 'compute',
    desc: 'Dedicated diagnostic and genomics capacity for the care system.',
    w: 2, h: 2, cost: 380, upkeep: 4, jobs: 8, housing: 0,
    power: -14, water: -8, compute: 20, pollution: 0.2, income: 4, buildTicks: 4,
    unlockCompute: 25,
  },
  community_dc: {
    type: 'community_dc', name: 'Community Compute Co-op', category: 'compute',
    desc: 'Volunteer-run racks on donated hardware. Slow, transparent, and yours.',
    w: 2, h: 2, cost: 240, upkeep: 4, jobs: 10, housing: 0,
    power: -6, water: -3, compute: 8, pollution: 0.1, income: 2, buildTicks: 3,
    unlockCompute: 15,
  },
};

export const BUILD_MENU_ORDER: BuildingType[] = [
  'dirt_road', 'road', 'avenue', 'highway',
  'house', 'apartment', 'midrise', 'highrise', 'arcology',
  'park', 'plaza', 'library', 'community_center', 'school', 'sports_complex', 'museum',
  'solar_farm', 'solar_array', 'coal_plant', 'nuclear_plant', 'water_plant', 'water_reclamation',
  'hospital', 'factory', 'auto_factory', 'office', 'retail',
  'edge_dc', 'community_dc', 'med_dc', 'cloud_dc', 'gov_dc', 'ai_campus',
];

/** Region-class names, indexed by tier. Mirrors TIERS in sim.ts. */
export const TIER_NAMES = ['Township', 'City', 'Metropolis', 'Megaregion'];
